apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app
  labels:
    app: birds-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birds-app
  template:
    metadata:
      labels:
        app: birds-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: birds-app
          image: REPLACED_BY_KUSTOMIZE
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi